import Head from 'next/head'
import Image from 'next/image'
import navbar from '../components/Home/Navbar'
import styles from '../styles/Home.module.css'
import Secondly from '../components/Home/Secondly'
import Navbar from '../components/Home/Navbar'
import Aquisitions from '../components/Home/Aquisitions'
import Books from '../components/Home/Books'
import Green from '../components/Home/Green'
import News from '../components/Home/News'
import Cards2 from '../components/Home/Cards2'
import Cards3 from '../components/Home/Cards3'
import Navbar2 from '../components/Home/Navbar2'
import Last from '../components/Home/Last'
import Categories from '../components/Home/Categories'
import Button from '../components/Home/Button'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        
      
      </Head>
     
<Navbar/>
<Secondly/>
<Aquisitions/>
<Books/>
<Green/>
<News/>
<Cards2/>

<Cards3/>
<div className='bg-green-100 mt-16 '>
<div className='pt-14'>
  <div class="text-4xl p-10 font-sans subpixel-antialiased font-bold text-purple-900">
   FIND IT FAST!
  </div>
<Categories/> 
</div>
<Books/>

<Button/>
</div>

<Navbar2/>

  <Last/>




      
    </div>
  )
}

